### ISSUE TITLE
If this project could save model use saved_model api?

### ISSUE THREAD

**Issue by StephenLee2016** [bshao001/ChatLearner#1]
Hi, you have done a great project, but if this project could save the model use saved_model api?

**Comment by bshao001** [comment]
I have never tried. But can you please explain the need and advantage of doing that?

**Comment by StephenLee2016** [comment]
I want to train a model and deploy it on the server， and if i use tensorflow serving，only saved_model format can be loaded.

**Comment by bshao001** [comment]
好的，不是很明白其中原因，不过很高兴能一起学习。当然使用微信。如果想讨论，可以先发邮件（中文即可）到我GMAIL邮箱，用户名同GITHUB的。

**Comment by bshao001** [comment]
A SOAP-based web service architecture has been implemented and can be used to address the deployment problem when the web environment is in Java or a language other than Python.

Since you have already had a solution, this issue will be closed. I would be very grateful if you could share your solution here.
