### ISSUE TITLE
running error when replace chinese corpus 

### ISSUE THREAD

**Issue by icecream0** [bshao001/ChatLearner#17]
error as follows:
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape [?,1024] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
[[Node: dynamic_seq2seq/encoder/rnn/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@dynamic_seq2seq/encoder/rnn/TensorArray"], dtype=DT_FLOAT, element_shape=[?,1024], _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/encoder/rnn/TensorArray, dynamic_seq2seq/encoder/rnn/TensorArrayStack/range, dynamic_seq2seq/encoder/rnn/while/Exit_1)]]
what's wrong? help me, please

**Comment by bshao001** [comment]
@icecream0 Did you try to run vocabgenerator.py in Data/Corpus folder to update the vocab.txt file after you modify the training data? Each time, you make changes to the training data, you have to recreate the vocab.txt so that it contains the new words you added. They can be Chinese or other languages, I assume.

However, I am not sure about the error you are encountering. But try to update the vocab, and let me know if that makes any differences. I would be very happy to give you a hand on that.

**Comment by icecream0** [comment]
First, Thanks a lot for your response. 
I run vocabgenerator.py to update the vocab.txt, but encounter the error in train_step
Details are as follows:
tensorflow.python.framework.errors_impl.InvalidArgumentError: pos 0 out of range for stringb'' at index 0
	 [[Node: Substr = Substr[T=DT_INT32](arg0, Substr/pos, Substr/len)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

**Comment by icecream0** [comment]
Thanks，I hava resolved the problem. It is possible to filter chinese string in method of _convert_to_tokens, so I make some changes, now model run successfully.
