### ISSUE TITLE
Not utilizing multiple GPU's even when batch size is changed.

### ISSUE THREAD

**Issue by dr-mccoy** [bshao001/ChatLearner#35]
Hi, I've changed my batch size to 128, 256, 512, 1024, 2048 (I get an OOM above 1000) none of them seem to utilize any but one of the GPU's. Tensorflow see's the other GPU's and so does Nvidia-SMI. I'm using 4x Nvidia Tesla P100's.

Nvidia-SMI:

![aaa](https://user-images.githubusercontent.com/36895941/36744140-e90670e0-1ba0-11e8-9f17-49d3a12df476.PNG)

Is this an issue on my part or something else?

**Comment by bshao001** [comment]
Hi, @dr-mccoy 
You are right. That's expected behavior: the implementation utilizes the compute ability of only the first GPU, with the memories from all GPUs. The original implementation supported model parallelism, but in a two-GPU case, it was even slower to train. In your case with 4 GPUs, you can probably try data parallelism. If you have a solution for that, please share with us.

**Comment by dr-mccoy** [comment]
Ah okay, thought I was going crazy. I'm going to stay with one GPU for the moment in that case. Will look into data parallelism on a later date.
