### ISSUE TITLE
get wrong result when use trained model to infer

### ISSUE THREAD

**Issue by QDPeng** [bshao001/ChatLearner#74]
the training stage is good，loss fall to 0.04，but when I use the trained mode to infer, the result is bad.
I don't know where is wrong.!!!!
I test BeamSearch and GreedySearch, this results is not good.
Can you help me?

**Comment by bshao001** [comment]
What did you mean by saying bad or wrong results? There are many reasons that impact the final outcome of a chatbot, way more than the model itself (yes, if you try Transformer model, you might get better result than using seq2seq/nmt). 

Firstly, what training data did you use? The quality of the training data is at least as important as the amount.
Secondly, based on the amount of training data, and a few other factors, you training may get over-fitted or under-fitted. 

You can check all these or, give me more details so that I can help you. If you have wechat, you can add me, and I might be able to give you detailed assistance.

**Comment by QDPeng** [comment]
this is my wechat id:anay333, you can add me

**Comment by QDPeng** [comment]
hello, I have a question: Why reverse the source sentence?

**Comment by bshao001** [comment]
With a simple google search, you should be able to find the answer. There are plenty of articles explaining this.
