### ISSUE TITLE
tokenizeddata

### ISSUE THREAD

**Issue by AlexanderYogurt** [bshao001/ChatLearner#8]
Hi Shao,
So I finished running the bottrain.py, but when I interact with the chat bot, it gives me really messy and random reply.

The training perplexity converges to ~1.3, so it seems the problem is not in the model. Have you ever faced this problem? Is it possible tokenizeddata.py didn't read the lines well?

Any insight is helpful before I give my code a full scan... Thanks!

Sample outputs:

> '>' Hello!
America members to.,...,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,..,...,..
> '>' Hi
Korea,,.,.,......,.,.,......!.!.!.!.!.!.!.!.!.!.!.!.!.

**Comment by AlexanderYogurt** [comment]
btw, instead running the default 60 epochs, I halted it at 30 epo after ppl --> 1.3.

**Comment by bshao001** [comment]
@AlexanderYogurt Other than running 30 epochs, did you make any other changes to the code, hyperparameters, or vocab size? I have never seen this problem myself. To me, ppl should not converge so quickly to 1.3 at epoch 30 (based on my experience). Please let me know the details of your changes (other than the code) so that I can try to give you a hint.

**Comment by AlexanderYogurt** [comment]
Thanks! It works now. Maybe I just train two models together and messed up the checkpoints. I retrained again and everything is fine.
